{
 "title": "AirGradient - General",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "device", "label": "Device Name", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "CO2 (Latest)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rco2{job=\"airgradient-$device\"}"
    }
   ]
  },
  {
   "title": "PM2.5 (Latest)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pm02{job=\"airgradient-$device\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "atmp{job=\"airgradient-$device\"}"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rhum{job=\"airgradient-$device\"}"
    }
   ]
  },
  {
   "title": "CO2 Over Time",
   "type": "graph",
   "gridPos": { "h": 13, "w": 22, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "expr": "rco2{job=\"airgradient-$device\"}",
     "legendFormat": "CO2"
    }
   ]
  },
  {
   "title": "PM2.5 Over Time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 22, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "conμgm3" }
   ],
   "targets": [
    {
     "expr": "pm02{job=\"airgradient-$device\"}",
     "legendFormat": "PM2.5"
    }
   ]
  }
 ]
}